### ISSUE TITLE
Too many responses

### ISSUE THREAD

**Issue by Turbozanik** [andriydruk/RxDNSSD#111]
Library responses as many times as you invoke browse method. So for the first invoke i will receive one response, for the second invoke i am receiving two responses, third time three responses and so on. So the number of responses for each invocation is n(number of browse method invocations ever made) instead of 1.

Please tell me what details do you need. Or maybe you can tell me how i can hot fix this.

**Comment by andriydruk** [comment]
Hi, you should stop browse when you finished looking for device
Please look at sample application
https://github.com/andriydruk/RxDNSSD/blob/master/app/src/main/java/com/github/druk/dnssdsamples/MainActivity.java#L132

**Comment by Turbozanik** [comment]
Actually i am unsubscribing every time i start a new browse. Can it be due to context leak in service?

But i will double check unsubscribing the disposable tomorrow.

**Comment by Turbozanik** [comment]
I have double checked i am unsubscribing every time i start a new browse. But i still have multiple responses.

**Comment by Turbozanik** [comment]
I am using your library like this, so its kinda global. 
![question](https://user-images.githubusercontent.com/7550948/71345422-5fb09c80-2576-11ea-88ab-8b539985a563.PNG)
Browse function is imlemented like this:
![question1](https://user-images.githubusercontent.com/7550948/71345498-98507600-2576-11ea-8a23-5ca00d7c9b01.PNG)

**Comment by andriydruk** [comment]
Could you check sample app? do you have the same problem with app from this repo?
What device do you use?

**Comment by Turbozanik** [comment]
I have checked the sample project and it is working fine, my later testing showed that library works well only if i am starting it from activity/fragment with activity context. Right now i am starting it with Application context and it seems that library starts new thred on each browse call, I have a multi module app, and i would really like to use this lib not in the ui layer, but inside logic layer.

**Comment by andriydruk** [comment]
Yes, library start new thread for every browser. Because of Apple NDK implementation of DNS-SD
Did you able to reproduce your issue with sample app and changing Context to Application context?

**Comment by Turbozanik** [comment]
> Yes, library start new thread for every browser. Because of Apple NDK implementation of DNS-SD
> Did you able to reproduce your issue with sample app and changing Context to Application context?

I will test it right now, will reply in half an hour.

**Comment by Turbozanik** [comment]
Mate sorry for waisting your time, i am an idiot, i missed one retry operator in my code, so i was spamming with browse calls every time.
