### ISSUE TITLE
Exciting project, I currently use ndk to write apps. Is there any example of using Embedded version in ndk?

### ISSUE THREAD

**Issue by xfirefly** [andriydruk/RxDNSSD#112]
Exciting project, I currently use ndk to write apps. Is there any example of using Embedded version in ndk?
Thanks.

**Comment by andriydruk** [comment]
No, for now, RxDNSSD provides only java API
But you can try to use C API directly - here entry point https://github.com/andriydruk/RxDNSSD/blob/master/dnssd/src/main/jni/JNISupport.c

**Comment by xfirefly** [comment]
Thanks very much.
