### ISSUE TITLE
Android NDK: Module jdns_sd depends on undefined modules: cutils log

### ISSUE THREAD

**Issue by proximous** [andriydruk/RxDNSSD#13]
I get the error in the title when trying to build the project with the latest SDK/NDK.  I've never used the NDK before so I'm not sure how to resolve this.  Do I need to find these modules and place them somewhere in my path?  Thanks.

**Comment by andriydruk** [comment]
Hi, this library is not part of public NDK API, but should work with latest NDK-bundle from Android SDK. 
Could you check:
1. version of NDK in source.properties file = 13.1.3345770
2. your min API in gradle and Android.mk = 14

**Comment by proximous** [comment]
Thanks for your reply. 
(1) my NDK is Pkg.Revision = 14.0.3770861 and 
(2) min API for the project is set to 16. I don't see it specified in the Android.mk from either ./library/src/main/jni/Android.mk or /library/src/main/jni/mdnsresponder/Android.mk. Am I looking in the right place? I haven't changed either of these files.

Could it be a change in the NDK version? I can try to see if I can downgrade to the version you mention.

I found this NDK change searching on this issue: [Module builds will now fail if they have any missing dependencies. To revert to the old behavior, set APP_ALLOW_MISSING_DEPS=true. See https://github.com/android-ndk/ndk/issues/208.](https://github.com/android-ndk/ndk/wiki/Changelog-r14-beta1#ndk-build) I tried adding `APP_ALLOW_MISSING_DEPS=true.` to the top of `./library/src/main/jni/Android.mk` and it now seems to build and work. Is this a good solution?

**Comment by andriydruk** [comment]
Ok, I will check a new version of NDK. It looks like an acceptable solution.
Sorry, my bad: Application.mk

**Comment by andriydruk** [comment]
Hi, I reviewed dependencies in Android.mk and remove unused ones. 
Now should works great with ndk-r14
