### ISSUE TITLE
Sample app for RxDNSSD

### ISSUE THREAD

**Issue by andriydruk** [andriydruk/RxDNSSD#14]
We need a simple application to demonstrate usage of RxDNSSD with:

1. [Apple DNSSD API](https://github.com/andriydruk/RxDNSSD/blob/master/library/src/main/java/com/apple/dnssd/DNSSD.java)
2. [My reactive DNSSD API](https://github.com/andriydruk/RxDNSSD/blob/master/library/src/main/java/com/github/druk/rxdnssd/RxDnssd.java)
3. [LiveData](https://developer.android.com/topic/libraries/architecture/livedata.html)&#x003C;BonjourService&#x003E;?

**Comment by chjan** [comment]
Yes, could you please provide discovery and resolve. thanks.

**Comment by andriydruk** [comment]
Hi, I sliced library into 2 layers: simple dnssd api and rxdnssd api.
Sample app was updated for both.
