### ISSUE TITLE
Upgrade to Rxjava 2

### ISSUE THREAD

**Issue by Pedramrn** [andriydruk/RxDNSSD#15]
Thank you

**Comment by dmfrey** [comment]
+1

**Comment by zhaohuaxishi** [comment]
+1

**Comment by azetor** [comment]
+1

**Comment by andriydruk** [comment]
Hi, all

I sliced my library to 2 layers: 
1. dnssd api 
2. rxjava api over dnssd

Now you can build rxjava 2 api over dnssd

**Comment by mannodermaus** [comment]
#33 was created to address this.

**Comment by andriydruk** [comment]
Done in version 0.9.7
