### ISSUE TITLE
The return value of reconfirmRecord

### ISSUE THREAD

**Issue by githubforzjm** [andriydruk/RxDNSSD#167]
Hi，
I found [DNSServiceReconfirmRecord](https://github.com/andriydruk/RxDNSSD/blob/bce8791516b6ee718cccab346066d55240d56194/dnssd/src/main/jni/mdnsresponder/mDNSShared/dnssd_clientstub.c#L1836) return a value, but [reconfirmRecord](https://github.com/andriydruk/RxDNSSD/blob/c4f96e1d83448438e0a698d4adb4ee1452044a71/dnssd/src/main/java/com/github/druk/dnssd/DNSSD.java#L547)return nothing

could you please add return value for this function?

**Comment by andriydruk** [comment]
Yes, looks like Apple forget return error code in their Java implementation here
https://github.com/andriydruk/RxDNSSD/blob/c4f96e1d83448438e0a698d4adb4ee1452044a71/dnssd/src/main/jni/JNISupport.c#L971

Feel free to create PR to make improvements to this project

**Comment by githubforzjm** [comment]
I add the return value for ReconfirmRecord temporarily by myself
Please let me know if you make any changes so I can use your library by build.gradle directly

**Comment by andriydruk** [comment]
Maybe would be better if you fix it via Pull Request?
[This is how to create Pull Request on Github](https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request)
