### ISSUE TITLE
Loss of service discovery

### ISSUE THREAD

**Issue by chjan** [andriydruk/RxDNSSD#17]
This is not a bug report. We find this api is working fine from a small footprint. There is one question related to Bonjour in general: What is best practice for discovering loss of services? In an embedded system of dedicated services, I need to discover loss of service as fast as possible. Does this imply a need to run a rediscovery on suitable intervals (10sec or so), or is there a setting to manipulate in order to achieve something similar?

**Comment by andriydruk** [comment]
It depends on what "loss" you mean: 
- If device makes unregister via mDNSResponder, then it should always work properly if you continue to listen to browse operation. 
- If device just kills the process or powered off, then it's a bad idea to use Bonjour. As I understand mDNSResponder contains some cache and device will be shown in `browse` some time

If you need more low-level API, take a look at official Bonjour Documentation
https://developer.apple.com/library/content/documentation/Cocoa/Conceptual/NetServices/Introduction.html

**Comment by chjan** [comment]
Not a bug, but we have trouble finding support-annotation library in repository for our embedded system that is stuck (for other reasons) with the gradle-wrapper 2.2.1

 

On our variant built for mobile phones we are using gradle-wrapper 3.3 and everything works fine and rock solid.

 

If you do not have a quick win to make our embedded system compliant, then:

 

Would it be possible to provide us with a jar file of your api? This would be more convenient than to build from source, and at least, it is worth a try.

 

It will suffice if you provide us with the aar file because it contains the jar also, and we can extract from that.

 

Else, we will build from source. 

 

Sorry for noising up your day, but thanks for any help.

 

Kind regards / Vennlig hilsen

 

Carl Henrik Janson

+47 951 048 00
