### ISSUE TITLE
ServiceLost() is not called when the service is closed without unregistration

### ISSUE THREAD

**Issue by mimminou** [andriydruk/RxDNSSD#182]
I'm building an Android app that needs to watch when services are found and lost on the network, i've noticed that onServiceLost() doesn't execute when a service is forcefully lost or closed (Network cable unpluging / Killing the service process etc...).

I've already experimented with [Android NSD](https://developer.android.com/training/connect-devices-wirelessly/nsd), it does detect them but it's unreliable in service resolution, i also tried [JmDNS](https://github.com/jmdns/jmdns) which is good but also has the same limitation of not detecing unregistred lost services, which brought me here.

Is there a way i could detect lost services in this situation ? if not right now could this be a feature in future releases ?

**Comment by andriydruk** [comment]
It's impossible to detect because services in this situation don't send Unregister events.
You should ping your devices on your own and found devices that don't respond.
