### ISSUE TITLE
How to continuously TXT records by using 0.9.13?

### ISSUE THREAD

**Issue by githubforzjm** [andriydruk/RxDNSSD#187]
browseDisposable = rxDnssd.browse(registerType, "")
                .compose(rxDnssd.resolve())
                .compose(rxDnssd.queryIPV4Records())
                .subscribeOn(Schedulers.io())
                .observeOn(AndroidSchedulers.mainThread())
                .subscribe(bonjourService -> {
                    if (bonjourService.isLost()) {
                        BonjourLog.i(TAG, "thread:" + logThreadId() + "serviceLost: " + bonjourService.toString());
                    } else {
                        BonjourLog.i(TAG, "thread:" + logThreadId() + "serviceFound: " + bonjourService.toString());

                        rxDnssd.queryTXTRecords(bonjourService)
                                .subscribeOn(Schedulers.io())
                                .observeOn(AndroidSchedulers.mainThread())
                                .subscribe(service -> {
                                    BonjourLog.i(TAG, "thread:" + logThreadId() + "TXTRecords changed: " + service.toString());
                                }, throwable -> {
                                    throwable.printStackTrace();
                                    BonjourLog.i(TAG, "thread:" + logThreadId() + "TXTRecords: " + throwable.getLocalizedMessage());

                                });

                    }
                }, throwable -> {
                    throwable.printStackTrace();
                    BonjourLog.i(TAG, "thread:" + logThreadId() + "Error: " + throwable.getLocalizedMessage());
                });

**Comment by githubforzjm** [comment]
@andriydruk  Can you provide some sample code for me to test？Thanks.

**Comment by githubforzjm** [comment]
@andriydruk Merry Christmas！！！
Any suggestions on this question？
Thanks！！

**Comment by andriydruk** [comment]
Hi, 
It looks like a bug. Your code should work well.
I pushed fix in #191
