### ISSUE TITLE
multicastlock is bugged in that it creates multiple acquires

### ISSUE THREAD

**Issue by neveroffline** [andriydruk/RxDNSSD#195]
I have a PR ready to submit and have fixed the issue.  I was able to observe the lock error doing 2 lookups (_tcp and _udp) every 10 seconds in a scheduled executor.  browseTCPService = dnssd.Browse().... and browseUDPService were stopped prior to each lookup, and resetup.  Results from each lookup were ~4 for a total of 8.

Basically onServicesStarting() is called multiple times and multicastLock.acquire() gets called multiple times.  Eventually Android will fatal with too many locks acquired.

My solution is 2 fold - optional constructors to set a enableMulticastLock at the DNSSD constructor level to entirely disable the locking as in some cases, people will already have their own - which is my case and I need to run regular consistent queries.

Second is wrapping multicastLock in a if(lockEnabled) with a double check on if(!multicastLock.isHeld()) multicastLock.acquire() for both ends of open/acquire and close.

`   
    // optional boolean to control our use of the multicastLock
    DNSSD(Context context, String lib, boolean enableMulticastLock) {
        this(context, lib, Looper.getMainLooper());
        this.lockEnabled = enableMulticastLock;
    }

    @Override
    public void onServiceStarting() {
        if(lockEnabled) { // optional enable/disable (default enabled)
            if (multicastLock == null) {
                synchronized (this) { // Double-check lock
                    if (multicastLock == null) {
                        WifiManager wifi = (WifiManager) context.getApplicationContext()
                                .getSystemService(Context.WIFI_SERVICE);
                        if (wifi == null) {
                            Log.wtf("DNSSD", "Can't get WIFI Service");
                            return;
                        }
                        multicastLock = wifi.createMulticastLock(MULTICAST_LOCK_NAME);
                        multicastLock.setReferenceCounted(true);
                    }
                }
            }
            // prevent multiple calls to acquire if we have it held
            // onServiceStarting may be called multiple times
            // fixes fatal crash on too many multicast locks held
            if(!multicastLock.isHeld()) multicastLock.acquire();
        }
    }

    @Override
    public void onServiceStopped() {
        if(lockEnabled) {
            if (multicastLock == null) {
                Log.wtf("DNSSD", "Multicast lock doesn't exist");
                return;
            }
            if(multicastLock.isHeld()) multicastLock.release();
        }
    }
`

**Comment by andriydruk** [comment]
Hi, looks good to me.
The only issue I see `isHelp -> acquire` and `isHeld -> release` should be synchronized as well

**Comment by andriydruk** [comment]
The general idea of this `onServiceStarting/onServiceStopped` is to calculate how many operations were started and how many stopped.
If the counter is zero -> lock should be released

As I understood in your project some `onServiceStopped` not called for some reason and it leads to over-acquired lock
I would rather investigate the issue with the lost `onServiceStopped`

And yes, we could add a new flag to disable multicast lock at all

**Comment by andriydruk** [comment]
Do you call `stop` method of DNSSDService returned from `DNSSD.browse()`?

**Comment by neveroffline** [comment]
Yes, I am creating two DNSSDServices, one browseTCPService and one browseUDPService - just before this, I check for either != null and do a browseTCPService.stop() on each and then null them, and recreate browseTCPService = dnssd.browse()... - every 10 secs - the issue.  I have submitted a commit.

**Comment by neveroffline** [comment]
Err rather, if  you give me access I can submit a commit - keeps bailing due to no permission.  Sorry.

**Comment by andriydruk** [comment]
Please create PR
Check this [Creating a pull request](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request)

**Comment by andriydruk** [comment]
and please show you the sample code as well 
I still have some doubts about this issue
