### ISSUE TITLE
Crash in register BonjourService Rx2Dnssd on Redmi3s with MIUI/Mashmallow

### ISSUE THREAD

**Issue by RahilRK** [andriydruk/RxDNSSD#198]
A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x1000006a346c4 in tid 11688 (DNS-SDEmbedded)
02-20 12:04:08.180 491-491/? A/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
02-20 12:04:08.180 491-491/? A/DEBUG: Build fingerprint: 'Xiaomi/land/land:6.0.1/MMB29M/V10.2.2.0.MALMIXM:user/release-keys'
02-20 12:04:08.180 491-491/? A/DEBUG: Revision: '0'
02-20 12:04:08.180 491-491/? A/DEBUG: ABI: 'arm64'
02-20 12:04:08.180 491-491/? A/DEBUG: pid: 11542, tid: 11688, name: DNS-SDEmbedded  >>> com.hksofttronix.sharemusic <<<
02-20 12:04:08.180 491-491/? A/DEBUG: signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x1000006a346c4
02-20 12:04:08.197 491-491/? A/DEBUG:     x0   0000007f92d4f180  x1   0000000000000000  x2   0000000000000008  x3   0000000000000030
02-20 12:04:08.197 491-491/? A/DEBUG:     x4   0000000000000000  x5   0000000000000040  x6   000000000000003f  x7   0000000000000000
02-20 12:04:08.198 491-491/? A/DEBUG:     x8   4001000006a346c4  x9   0000005594f6dae0  x10  0000000000000046  x11  0000007f92d6ecbe
02-20 12:04:08.198 491-491/? A/DEBUG:     x12  0000000000000000  x13  000000000000006c  x14  000000000000006c  x15  000000000000002b
02-20 12:04:08.198 491-491/? A/DEBUG:     x16  0000007f92d4ce40  x17  0000007faeb55100  x18  0000007fabab3000  x19  0000007f92d63ac0
02-20 12:04:08.198 491-491/? A/DEBUG:     x20  0000007f92d4f180  x21  0000007f92d4f188  x22  0000007f92d6cc20  x23  0000007f92d4f180
02-20 12:04:08.198 491-491/? A/DEBUG:     x24  0000000043167879  x25  0000007f92d6cc2a  x26  0000000000000020  x27  0000007f92d4f1f0
02-20 12:04:08.198 491-491/? A/DEBUG:     x28  0000007f92cc8c33  x29  0000007f92cc81c0  x30  0000007f92cfbb54
02-20 12:04:08.198 491-491/? A/DEBUG:     sp   0000007f92cc8170  pc   0000007f92cfbc3c  pstate 0000000080000000
02-20 12:04:08.229 491-491/? A/DEBUG: backtrace:
02-20 12:04:08.230 491-491/? A/DEBUG:     #00 pc 000000000000fc3c  /data/app/com.hksofttronix.sharemusic-1/lib/arm64/libjdns_sd_embedded.so
02-20 12:04:08.230 491-491/? A/DEBUG:     #01 pc 00000000000116b8  /data/app/com.hksofttronix.sharemusic-1/lib/arm64/libjdns_sd_embedded.so
02-20 12:04:08.230 491-491/? A/DEBUG:     #02 pc 000000000002ed34  /data/app/com.hksofttronix.sharemusic-1/lib/arm64/libjdns_sd_embedded.so
02-20 12:04:08.230 491-491/? A/DEBUG:     #03 pc 000000000002eb50  /data/app/com.hksofttronix.sharemusic-1/lib/arm64/libjdns_sd_embedded.so
02-20 12:04:08.230 491-491/? A/DEBUG:     #04 pc 000000000002f12c  /data/app/com.hksofttronix.sharemusic-1/lib/arm64/libjdns_sd_embedded.so
02-20 12:04:08.230 491-491/? A/DEBUG:     #05 pc 000000000003ca54  /data/app/com.hksofttronix.sharemusic-1/lib/arm64/libjdns_sd_embedded.so
02-20 12:04:08.230 491-491/? A/DEBUG:     #06 pc 000000000003cb84  /data/app/com.hksofttronix.sharemusic-1/lib/arm64/libjdns_sd_embedded.so
02-20 12:04:08.230 491-491/? A/DEBUG:     #07 pc 00000000027321d8  /data/app/com.hksofttronix.sharemusic-1/oat/arm64/base.odex (offset 0x1615000) (int com.github.druk.dnssd.DNSSDEmbedded.nativeLoop()+124)
02-20 12:04:08.230 491-491/? A/DEBUG:     #08 pc 0000000001b05cd0  /data/app/com.hksofttronix.sharemusic-1/oat/arm64/base.odex (offset 0x1615000) (void com.github.druk.dnssd.DNSSDEmbedded$1.run()+948)
02-20 12:04:08.231 491-491/? A/DEBUG:     #09 pc 000000000011ea24  /system/lib64/libart.so (art_quick_invoke_stub+580)
02-20 12:04:08.231 491-491/? A/DEBUG:     #10 pc 000000000012d8dc  /system/lib64/libart.so (_ZN3art9ArtMethod6InvokeEPNS_6ThreadEPjjPNS_6JValueEPKc+176)
02-20 12:04:08.231 491-491/? A/DEBUG:     #11 pc 0000000000430e24  /system/lib64/libart.so (_ZN3art35InvokeVirtualOrInterfaceWithJValuesERKNS_33ScopedObjectAccessAlreadyRunnableEP8_jobjectP10_jmethodIDP6jvalue+460)
02-20 12:04:08.231 491-491/? A/DEBUG:     #12 pc 000000000045f6d0  /system/lib64/libart.so (_ZN3art6Thread14CreateCallbackEPv+744)
02-20 12:04:08.231 491-491/? A/DEBUG:     #13 pc 00000000000677c4  /system/lib64/libc.so (_ZL15__pthread_startPv+52)
02-20 12:04:08.231 491-491/? A/DEBUG:     #14 pc 000000000001c644  /system/lib64/libc.so (__start_thread+16)
02-20 12:04:08.654 491-491/? A/DEBUG: Tombstone written to: /data/tombstones/tombstone_05
02-20 12:04:08.654 491-491/? E/DEBUG: AM write failed: Broken pipe

**Comment by andriydruk** [comment]
What device do you use? What API?
Why do you decide to switch to an Embedded version? Do you have the same issue with Bindable?

**Comment by RahilRK** [comment]
Bro I am new in using NSD and socket.... can you suggest me which I should use
DNSSD,
RxDNSSD or
Rx2DNSSD
(Bindable or Embedded version) ?

**Comment by andriydruk** [comment]
I would recommend you to try Bindable. It's faster and uses the system library from your device.
DNSSD, RxDNSSD, or Rx2DNSSD it doesn't matter. These are a bunch of different APIs for 1 implementation, use whatever comfortable for you.

DNSSD is a classical API with operations and callbacks
RxDNSSD is a reactive API based on RxJava1 (a wrapper around DNSSD)
Rx2DNSSD is a reactive API based on RxJava2 (a wrapper around DNSSD)

**Comment by RahilRK** [comment]
**Thanks a lot buddy cheerzzzz**
