### ISSUE TITLE
Migration away from JCenter

### ISSUE THREAD

**Issue by outadoc** [andriydruk/RxDNSSD#199]
Hello,

Thank you for this project!

As you may know, JCenter and Bintray are going to be [shut down soon](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/) (no more submissions after March 31st 2021). 

RxDNSSSD and the related dependencies don't seem to be available anywhere else right now. It would be great if the artifacts could be published to Maven Central or some other repository.

Thank you 🙂

**Comment by andriydruk** [comment]
Hi, I'm working on migration to MavenCentral
Now waiting for approval from Sonatype

**Comment by outadoc** [comment]
Great, thank you!

**Comment by andriydruk** [comment]
New version 0.9.15 already on Maven Central
Old versions still in progress...

**Comment by andriydruk** [comment]
https://github.com/andriydruk/RxDNSSD/releases/tag/0.9.15
