### ISSUE TITLE
Wrong version of support-annotations

### ISSUE THREAD

**Issue by mpuz** [andriydruk/RxDNSSD#20]
Error:Failed to resolve: com.android.support:support-annotations:26.0.1

**Comment by andriydruk** [comment]
The current version of support annotations is 26.0.1:
https://developer.android.com/topic/libraries/support-library/packages.html#annotations

Please check that you switched from local repo to google maven. New versions of support library distributed only through google's own maven repo:
https://developer.android.com/topic/libraries/support-library/setup.html
