### ISSUE TITLE
txtRecord is getting null

### ISSUE THREAD

**Issue by RahilRK** [andriydruk/RxDNSSD#204]
- 0.9.15 txtRecord is getting null, but in 0.9.13 is getting proper

**Comment by andriydruk** [comment]
Hi. Could you reproduce this bug in a sample app or [Bonjour Browser](https://github.com/andriydruk/BonjourBrowser)?

**Comment by phatblat** [comment]
Did this get fixed by #203 in 0.9.16?

**Comment by andriydruk** [comment]
Yes
