### ISSUE TITLE
🚀 New Release?

### ISSUE THREAD

**Issue by phatblat** [andriydruk/RxDNSSD#214]
It's been almost a year since [0.9.16](https://github.com/andriydruk/RxDNSSD/releases/tag/0.9.16) was released and I was hoping to get the fix in #211 soon. Is there anything I can help with?

**Comment by StevenFY** [comment]
@andriydruk : Most appreciate 👍

**Comment by andriydruk** [comment]
New version 0.9.17 was released in December. Just update your dependency
https://search.maven.org/artifact/com.github.andriydruk/dnssd
