### ISSUE TITLE
Check Not Null DMX Conflict

### ISSUE THREAD

**Issue by alissongodoi** [andriydruk/RxDNSSD#25]
I was trying to compile for Android -4.4 and I got a DMX File Conflict for the Java Annotations for CheckNotNull file class.

Error on running app:
:app:transformClassesWithDexForDebug Ljavax/annotation/CheckForNull;

I had to add the following to compile successfully:
    compile ('com.github.andriydruk:rxdnssd:0.9.1') {
        exclude group : 'com.android.support', module: 'support-annotations'
        exclude group: 'com.google.code.findbugs', module: 'annotations'
    }

**Comment by andriydruk** [comment]
Fixed in [0.9.3](https://github.com/andriydruk/RxDNSSD/releases/tag/0.9.3)
