### ISSUE TITLE
rx2dnssd not available via jcenter

### ISSUE THREAD

**Issue by G00fY2** [andriydruk/RxDNSSD#35]
I am not very familiar with publishing libraries but it seems that unlike your previous ones **rx2dnssd** is not available via jcenter. I have problems resolving this dependency in Android Studio even though my repositories look like this:
```
repositories {
    google()
    jcenter()
    maven { url "https://jitpack.io" }
    mavenCentral()
  }
```

On bintray the `Linked to ` section is empty too.

Or is there any other way to resolve it?

Greetings

**Comment by andriydruk** [comment]
Hi, 
I sent request for adding rx2 package, but it's usually take some time. 
You can use directly my maven repo for now
```
maven { url 'https://dl.bintray.com/andriydruk/maven/' }
```
When I recieve email from Bintray, I will close this issue.

I'm sorry for your inconvenience.

**Comment by G00fY2** [comment]
Thank you very much!
Wasn't aware that requests on jcenter take some time. Did not want to appear impatient.:D Will test rx2 within the next day.

**Comment by thehellmaker** [comment]
I still dnt see this change in https://mvnrepository.com/artifact/com.github.andriydruk 

How can I import rx2dnssd into my android app

**Comment by andriydruk** [comment]
I use `jcenter()` for distribution packages:

```
buildscript {
    repositories {
        google()
        jcenter()
    }
}
```

```
dependencies {
    implementation 'com.github.andriydruk:rx2dnssd:0.9.7'
}
```
