### ISSUE TITLE
queryRecord on type 16 never answers nor fails

### ISSUE THREAD

**Issue by crachou** [andriydruk/RxDNSSD#39]
Hiya,
Using version 0.9.7 of the DNSSD library, calling to queryrecord() never answers nor fails for type 16 (TXT record).
Works perfectly fine with type 1 or 28, and resolve is able to display the initial value for TXT record.
Tested on a Samsung Galaxy S7 with Android 7.0

Steps to reproduce
-----------------------
Service is published using dns-sd:
dns-sd -U
or
dns-sd -R Toto _testupdate._tcp . 1337 [foo=bar]

Monitored using:
dns-sd -Q Test._testupdate._tcp.local 16 1

Query for records after browsing and resolving:
            dnssd.queryRecord(0, ifIndex, hostName, 1, 1, listener);
            dnssd.queryRecord(0, ifIndex, hostName, 16, 1, listener);
            dnssd.queryRecord(0, ifIndex, hostName, 28, 1, listener);

Service is found, resolved, queries for types 1 & 28 are answered, but not for type 16

04-12 18:10:00.436 30004-30004/com.xxx.zeroconf D/TAG: Found  Toto _testupdate._tcp. local.
04-12 18:10:00.440 30004-30004/com.xxx.zeroconf D/TAG: Resolved NEO-L183.local.
04-12 18:10:00.441 30004-30004/com.xxx.zeroconf D/TAG: Toto._testupdate._tcp.local. NEO-L183.local. 1337
04-12 18:10:00.441 30004-30004/com.xxx.zeroconf D/TAG: TXT RECORD [foo bar]
04-12 18:10:00.449 30004-30004/com.xxx.zeroconf D/TAG: queryAnswered -  rrtype 1 rrclss 1 - fullName NEO-L183.local. address /192.168.1.105 
04-12 18:10:00.450 30004-30004/com.xxx.zeroconf D/TAG: queryAnswered -  rrtype 28 rrclss 1 - fullName NEO-L183.local. address /[replaced_for_confidentiality]

**Comment by andriydruk** [comment]
@crachou yes, you are right `queryRecord` in my library supports only types 1 and 28. I supposed that developer will use `queryRecord` only for resolving ip address and use `resolve` for TXT records

But it's a good point, i will fix that soon
Thank you

**Comment by andriydruk** [comment]
Hi, @crachou  I've just published new version 0.9.8-beta1 with new API for querying IP and TXT records
`queryRecord` now return byte[] and you can use it for any types
Also I added `queryTXTRecord` to rxdnssd and rx2dnssd

**Comment by andriydruk** [comment]
New stable version includes this API as well
https://github.com/andriydruk/RxDNSSD/releases/tag/0.9.10
