### ISSUE TITLE
IpV6 support

### ISSUE THREAD

**Issue by RobartGmbH** [andriydruk/RxDNSSD#40]
Can we tell me what is the status regarding ipv6?

**Comment by andriydruk** [comment]
There are 3 API:  `queryRecords`, `queryIPV4Records` and `queryIPV6Records`
`queryRecord` should merge answers from both ipv4 and ipv6

**Comment by RobartGmbH** [comment]
IpV6 standard says there can be multiple ipv6 addresses with different scopes but only one it is returned by the discovery and in our case linklocal address. 
We would like to go for the unique address with a global scope which is not return by the discovery.
Can you tell me more in this direction?

**Comment by andriydruk** [comment]
Ok, we definitely should fix it in future versions.

For now you can use DNSSD API without Rx. This API return every discovered address .
Or try to fix it in Rx. BonjourServices should have list of addresses instead of IPV4 and IPV6 properties.

**Comment by RobartGmbH** [comment]
Can we talk shortly on private/chat so I know - in case I want to fix it - what to do?

**Comment by andriydruk** [comment]
Hi, I've just published new version 0.9.8-beta1 with new API for querying  IP and TXT records
Use [queryIPRecords](https://github.com/andriydruk/RxDNSSD/blob/0.9.8-beta1/rx2dnssd/src/main/java/com/github/druk/rx2dnssd/Rx2Dnssd.java#L99) to discover all IP addresses of service
Also use [getInetAddresses](https://github.com/andriydruk/RxDNSSD/blob/0.9.8-beta1/rx2dnssd/src/main/java/com/github/druk/rx2dnssd/BonjourService.java#L205) to retrieve list of all addresses of service

**Comment by RobartGmbH** [comment]
Hi,
Sure, I started testing already.

**Comment by andriydruk** [comment]
Hi, please check version 0.9.10. 
It has API for continuously querying IP addresses. This should help
