### ISSUE TITLE
Java support

### ISSUE THREAD

**Issue by Abu-Abdullah** [andriydruk/RxDNSSD#41]
Hi,

is there any plan to support this library on linux using Java openJDK. it will add a lot of value

**Comment by andriydruk** [comment]
No, this is port of mDNSResponder for Android
For Linux OpenJDK you can use official Apple mDNSResponder https://opensource.apple.com/tarballs/mDNSResponder/

if you prefer RxDNSSD library API, you can use it with official Apple mDNSResponder with little changes in package names
