### ISSUE TITLE
Rx2DnssdEmbedded browse has  time limit?

### ISSUE THREAD

**Issue by wangsuicheng** [andriydruk/RxDNSSD#42]
The browsing stop automatically in about 25 minutes and I could not receive BonjourService any more but if restart the app...
test on the Android 6.0.1 device

**Comment by andriydruk** [comment]
No, browsing doesn't have any time limits
Did you reproduce the problem in a sample app? Did you do something to prevent a device from sleeping?

**Comment by wangsuicheng** [comment]
@andriydruk 
Q: Did you reproduce the problem in a sample app? 
A: No, I just use Rx2DnssdEmbedded browser method

Q: Did you do something to prevent a device from sleeping?
A: Our device plugged in USB will never stand by and sleep, wifi is the same

**Comment by wangsuicheng** [comment]
I use Rx2DnssdBindable instend of Rx2DnssdEmbedded, it's browsing doesn't have any time limits

**Comment by andriydruk** [comment]
Thanks, I will investigate this issue

**Comment by andriydruk** [comment]
Hi, please check new version: I added wifi locks, this should prevent wifi radio turning off
https://github.com/andriydruk/RxDNSSD/releases/tag/0.9.10

I'm going to close this issue. If it doesn't help please reopen it
