### ISSUE TITLE
Invoke-customs are only supported starting with Android O (--min-api 26)

### ISSUE THREAD

**Issue by perihanmirkelam** [andriydruk/RxDNSSD#43]
I got this error when I try to implement 
'com.github.andriydruk:dnssd:0.9.7'  and 
"com.github.andriydruk:rxdnssd:0.9.7"
library on "min api:19 and target api:26" app:

Android issue:
Invoke-customs are only supported starting with Android O (--min-api 26)
Message{kind=ERROR, text=Invoke-customs are only supported starting with Android O (--min-api 26), sources=[Unknown source file], tool name=Optional.of(D8)}

Java compile:
Caused by: com.android.builder.dexing.DexArchiveBuilderException: Failed to process 
   /home/.../.gradle/caches/transforms-1/files-1.1/dnssd- 
   0.9.7.aar/da29e81bbce2608f3cdc2603f6618baf/jars/classes.jar
Caused by: com.android.builder.dexing.DexArchiveBuilderException: Error while dexing.
Caused by: com.android.tools.r8.CompilationFailedException: Compilation failed to complete
Caused by: com.android.tools.r8.utils.AbortException

So I implement v0.9.1 both.

**Comment by perihanmirkelam** [comment]
It works: 

android{
compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

**Comment by divs1896** [comment]
Thanks @perihanmirkelam
