### ISSUE TITLE
Which one to use for android mDNS alternative?

### ISSUE THREAD

**Issue by kostadin24** [andriydruk/RxDNSSD#44]
Hello,
I found 2 projects:
andriydruk/BonjourBrowser
andriydruk/RxDNSSD

Both show mDNS messages in the network.
Wich one is better to use as replacement of mDNS provided by Android OS?
Thanks in advance!

**Comment by andriydruk** [comment]
Hi, 

RxDNSSD is a library. 
BonjourBrowser is an android application that shows how to use this library.

**Comment by kostadin24** [comment]
Thanks.
