### ISSUE TITLE
mDNS discovery starts very slow.

### ISSUE THREAD

**Issue by kostadin24** [andriydruk/RxDNSSD#46]
Hello,
Discovery starts very slow on Samsung Galaxy S8 (Android 8.0).
On BonjourBrowser app discovery is started with RxDnssdBindable.
Switched to RxDnssdEmbedded and started quick.
Not sure if this fixed problem because meanwhile I restarted phone.

Currently discovery is with RxDnssdEmbedded. Will wait feedback from testers.
Do you have feedback from for other Samsung users with Android 8.0?

Best regards

**Comment by kostadin24** [comment]
On Samsung Galaxy Tab S2 with android 7.0
works for 1 minute and stops. Begin to work only after device restart.

**Comment by andriydruk** [comment]
Hi, did you have this issue with both Bindable and Embedded versions?
I tested with Samsung Edge 7 with Android 8.0.0, don't have any issues
Did you make discovering in the foreground? Did you have issues in my app Service Browser?

**Comment by kostadin24** [comment]
Hi,
I use discovery in foreground. Wasn't sure about my code. So I used Service
browser -last version from github.
Problem is not permanent, it appears from time to time. Let say 30% of time
works. And when works discovery starts very slow - about 15 sec.
Restarting rouret, phone and devices with mDNS services helps in 90% of
cases. If not restart and leave all untouched - after half hour or more
problem dissapears. No suspicious messages in logcat.
And one new fact - not only Samsung devices with Android 7 and high have
problem. Yesterday ASUS tablet with Android 6.0 discovered mdns very slow.

**Comment by kostadin24** [comment]
Forgot to say using bindable or embedded didnt make difference for tested
Samsung devices.
After using different network tools fell like some of them change devuce
state and mDNS again starts to work.

**Comment by andriydruk** [comment]
What about another library? Did you try jmdns or Android NSD? Does it start quick?

**Comment by kostadin24** [comment]
Have a lot of work this days. Hope to find time to test it.

**Comment by kostadin24** [comment]
We probably have bad hardware here. Devices working fine with Xiaomi and not worlking at all with Samsung. Testers analyzed network traffic and result is - Xiaomi device can ping mDNS devices, but Samsung fails in almost all tests.

**Comment by kostadin24** [comment]
My coworker user Wireshark to watch network.
In case with Samsung devices - mDNS responses are longer than responses with non Samsung devices.

Attached file is with Samsung devices.
![mdns_issue](https://user-images.githubusercontent.com/15262632/46345486-68edda80-c64d-11e8-8a29-4439fdb19505.png)

**Comment by andriydruk** [comment]
Yes, just add a breakpoint in Java or C code in Android Studio
and choose `Debugger Type' == Dual

 Did you have a chance to try jmdns or Android NSD?

**Comment by kostadin24** [comment]
Protocol IGMP is missing on problematic devices. Without ICMP works very rarely. With IGMP works better/again not 100% but 70-80%/.

**Comment by kostadin24** [comment]
Comparing network messages with iOS -> IGMP is not implemented on many android devices and may be is involved.

**Comment by andriydruk** [comment]
Samsung Galaxy S8 as well? I heard about devices that don't support multicasts, but I've never had access to one.

It would be nice if we have an ability to detect a device that doesn't support `IGMP` and show a message to a user

**Comment by kostadin24** [comment]
Unfortunately I found issue 2 weeks before release date :( 
Maybe brute force scan will be used in case of no mDNS devices found.

**Comment by kostadin24** [comment]
Finally - some of android devices/mostly Samsung with android 8.0 and 8.1/ use IGMPv3 with broken logic.
Devices that implement IGMPv2 and IGMPv3 works fine at all. But some devices have version of android that use IGMPv3 with strangle broken behaviour. This causes router to not send them multicast packages.
So because this is in operating system - we can not fix this. In case of IGMPv3 with broken logic - will use other ways for discovery.
