### ISSUE TITLE
Discovery doesn't work with Android 9

### ISSUE THREAD

**Issue by pziesig** [andriydruk/RxDNSSD#54]
I am having some trouble to get this library working on every Android 9 smartphone i have tested on. This problem is only occouring on Android 9 and the same code runs without any problem on all lower versions. 

This is a small code snippet that i use currently to test the mDNS-Discovery:
```kotlin
    var rxDnssd = RxDnssdBindable(context)
    rxDnssd.browse("_https._tcp", "local.")
        .compose(rxDnssd.resolve())
        .compose(rxDnssd.queryRecords())
        .subscribeOn(Schedulers.io())
        .observeOn(AndroidSchedulers.mainThread())
        .subscribe({ Log.d("DNSSD", "foundService: $it" },
                   { throwable -> Log.e("DNSSD", "error", throwable) })
```
When this code gets executed there are no corresponding debug or error messages in the logs.

I have not seen any api changes with Android 9 to why this should not work anymore and i am clueless at this point. 

Any help with this is appreciated!

**Comment by pziesig** [comment]
I discovered this issue https://github.com/andriydruk/RxDNSSD/issues/38 and i could fix my problem with the described fix from eman8519.

```
<uses-permission android:name="android.permission.CHANGE_WIFI_MULTICAST_STATE"/>`
```
```
WifiManager wifi = (WifiManager) mContext.getSystemService(Context.WIFI_SERVICE);
WifiManager.MulticastLock multicastLock = wifi.createMulticastLock("multicastLock");
multicastLock.setReferenceCounted(true);
multicastLock.acquire();
.
.
multicastLock.release(); // release after browsing
```

I have also updated to version 0.9.11 RxDNSSD from 0.9.10 and there does come an appropriate exception message if you try to do multicast without acquiring it first.

```
java.lang.RuntimeException: MulticastLock under-locked com.github.druk.dnssd.DNSSD
        at android.net.wifi.WifiManager$MulticastLock.release(WifiManager.java:3461)
        at com.github.druk.dnssd.DNSSD.onServiceStopped(DNSSD.java:578)
        at com.github.druk.dnssd.DNSSDBindable.onServiceStopped(DNSSDBindable.java:44)
        at com.github.druk.dnssd.InternalDNSSDService.stop(InternalDNSSDService.java:21)
        at com.github.druk.rxdnssd.RxDnssdCommon$DNSSDServiceAction.call(RxDnssdCommon.java:244)
        at rx.subscriptions.BooleanSubscription.unsubscribe(BooleanSubscription.java:71)
```

**Comment by andriydruk** [comment]
Hi, @pziesig
Sorry for long respond. It already known issue and yes it fixed with `multicastLock`

I'm working on fixing it inside my library, but don't have enough time to test it properly. 
I will notify you when a fixed version will be published in JCenter
