### ISSUE TITLE
A method to flush the cache

### ISSUE THREAD

**Issue by Abu-Abdullah** [andriydruk/RxDNSSD#66]
Hi,

Is there a way to implement a method to invalidate the cache. we need to wait usually for some time until the cache is refreshed. 
this is useful for example in case some devices are powered off. the discovery will still show you the old device until you close the device from the history. finish() will not be enough, or recreate the same activity again. i believe it is stored in the native code until the app exit() totally

i have seen this method reconfirmRecord(), but i do not know how to use it or if it will help.

in addition, is their any API document

**Comment by andriydruk** [comment]
If you use Bindable version, DNSSD uses 1 cache for all process. It located in OS, not in native code of your app.

From my knowledge of DNSSD, `reconfirmRecord` is the proper way to invalidate the cache of service.
Good documentation here, almost all functions and args are the same
https://developer.apple.com/documentation/dnssd/1804726-dnsservicereconfirmrecord
