### ISSUE TITLE
Use mDNS in service

### ISSUE THREAD

**Issue by kostadin24** [andriydruk/RxDNSSD#70]
Hello,
Is it possible to use library for network discovery outside activities? Is it possible to make WiFi multilock outside activity?
Other concerns are because outside activity I don't know when to stop discovery - not sure if app is going to background or going to be killed.

**Comment by andriydruk** [comment]
Probably you can try to run foreground service and use its context for DNSSD.
Service should be stopped by the system before the process kill
https://developer.android.com/guide/components/services#Foreground

**Comment by kostadin24** [comment]
Just moved bindable version to app class. Works fine. The only problems are samsung devices. From time to time they polute network an I have to reboot router.
According to google when app is stopped lock made inside app is released.
