### ISSUE TITLE
Include required java 1.8 in gradle below Android API 24 in README

### ISSUE THREAD

**Issue by Xerusial** [andriydruk/RxDNSSD#71]
I am developing 2 apps(min API 23 and API 26)  and a library (min API 23) shared by both.
To sucessfully compile RxDNSSD on API 23, Java 1.8 support is needed, because it is
needed for C invokes.
So please add to your README, that below API 24 the following is needed in Gradle:
```
compileOptions 
        sourceCompatibility 1.8
        targetCompatibility 1.8
```

And strangely, because I did only have the `compileOptions` in my min API 23 app and not in the library nor the other app, I even got a SIGSEGV on this invoke in DNSSDEmbedded:

`handler.removeCallbacks(DNSSDEmbedded::nativeExit);`

Adding the `compileOptions` to all three resolved the issue.

**Comment by PSGXerus** [comment]
Also, the current README states that DNSSDEmbedded constructor is not needing an argument. But in 0.9.13 it needs the current context as argument.

**Comment by PSGXerus** [comment]
Other than that: great work, this library saved me from getting crazy over the built-in NsdManager :S

**Comment by andriydruk** [comment]
Hi, thanks for the feedback I will update documentation soon

Nowadays devs don't add `compileOptions 1.8` by default?
When I started this project it was `must have` at all projects 😅
